### ISSUE TITLE
res is null. $scope.signup angular error

### ISSUE THREAD

**Issue by tarunhere** [ttkalec/laravel5-angular-jwt#1]
![jwt error](https://cloud.githubusercontent.com/assets/4122496/7932778/57501584-0938-11e5-97e0-2dbb78e412b1.png)

I have setup this project in local, but on submitting I am getting this error from the angularjs.
Please help me understand this.

Also, I have implemented roles and permission from Entrust package, How can I implement JWT to work with Entrust roles package? I had installed JWT in same project, but it had crashed my application and I had to reset all by removing jwt package.
Any help/guide will be highly appreciated.

**Comment by ttkalec** [comment]
Seems like you haven't set up the CORS on the Laravel side correctly, so the signup requests fail, returning you null in the response.
