### ISSUE TITLE
Auto Refresh Token

### ISSUE THREAD

**Issue by juan-morales** [ttkalec/laravel5-angular-jwt#2]
It would be a good idea to improve the code in order to handle autorefresh token using the tymon/jwt-auth package ... but with the 1.0.0l version of it.

I would be glad to contibute to the repo, but many people come to the repo by your article in toptal site.

Anyways ... just consider it

**Comment by ttkalec** [comment]
Hi Juan. Thanks for the suggestion.
The Toptal article is over 3 years old now I think, and while the underlying principles of JWT and packages used are still relevant the whole article and the code base are due for a refresh. I don't want to change the code without updating the article as well to keep them in sync.

I will think about creating a separate updated code examples and maybe one more using Vue.Js.

**Comment by juan-morales** [comment]
that would be great ttkalec. good luck with that
